---
title: "10x PAH NucSeq - Data Integration"
author: '[Yvon Mbouamboua](mbouamboua@ipmc.cnrs.fr)'
output:
  html_document: default
  html_notebook: default
date: 'Compiled: `r Sys.Date()`'
---

# Setting parameters

```{r setup, include=T, warning=FALSE}

options(future.globals.maxSize = 80000*1024^2)
main.dir <- "/data/data_mbouamboua/projects/10x_htap_nucseq/"
input.dir <- paste(main.dir, "data", "cellranger", sep = "/")
input.file <- "filtered_feature_bc_matrix"
out.dir <- paste0(main.dir, "processing/")
if(!dir.exists(out.dir)){dir.create(file.path(out.dir), recursive = T, showWarnings = F)}
set.seed(4743)

```

# Require R packages and functions

```{r}

suppressPackageStartupMessages({
  library(Seurat)
})

```


# Integration using RPCA

```{r fig.width=10, fig.height=7}

obj.list <- readRDS(paste(out.dir, "obj.list.rds", sep = "/"))

obj.list <- lapply(X = obj.list, FUN = function(x) {
  x <- NormalizeData(x, verbose = T)
  x <- FindVariableFeatures(x, verbose = T)
})
invisible(gc())

features <- SelectIntegrationFeatures(object.list = obj.list)

obj.list <- lapply(X = obj.list, FUN = function(x) {
  x <- ScaleData(x, features = features, verbose = T)
  x <- RunPCA(x, features = features, verbose = T)
})


# Identify anchors and integrate datasets using RPCA
anchors <- FindIntegrationAnchors(object.list = obj.list, 
                                  reduction = "rpca", 
                                  anchor.features = 36601, 
                                  dims = 1:30, 
                                  verbose = T)
rm(obj.list)
invisible(gc())

integrated <- IntegrateData(anchorset = anchors, dims = 1:30, verbose = F)
rm(anchors)
invisible(gc())

# Select variable features
integrated <- FindVariableFeatures(integrated, nfeatures = 36601)
features <- VariableFeatures(integrated)
integrated <- ScaleData(integrated, verbose = T)
integrated <- RunPCA(integrated, features = features, verbose = T)
invisible(gc())

# Finding the numbers of PCs for UMAP
best_pcs <- Get_PCs(integrated, reduction_name = "pca")
best_pcs <- min(best_pcs)

# Constructing UMAP
integrated <- RunUMAP(integrated, dims = 1:best_pcs, reduction = "pca",verbose = T)
integrated <- FindNeighbors(integrated, dims = 1:best_pcs, reduction = "pca")
integrated <- FindClusters(object = integrated, resolution = c(0.2,3), graph.name = "integrated_snn")
invisible(gc())

#Plot umap
DimPlot(integrated, group.by = c("orig.ident"), label = F)  + DarkTheme()
DimPlot(integrated, group.by = c("seurat_clusters"), label = T, label.color = "white") + NoLegend() + DarkTheme()

```


# Session info

```{r session_info}

utils::capture.output(devtools::session_info())

```
